#!/usr/bin/env bash

tw_log "Installing home-brew..."
tw_execute /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

tw_log "Tapping homebrew/cask-fonts..."
tw_execute brew tap homebrew/cask-fonts

tw_log "Installing svn as a dependency for a few packages"
tw_execute brew install svn
