#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo xbps-install -S \
           cryptsetup \
           efibootmgr \
           polkit \
           dbus \
           tmux \
           fish-shell \
           fd \
           lsd \
           bat \
           ncdu \
           ripgrep \
           fzf \
           vim \
           emacs-gtk3 \
           mpv \
           aspell \
           aspell-en \
           git \
           tig \
           ranger \
           cryfs \
           rsync \
           zip \
           unzip \
           btop \
           psmisc \
           udisks2 \
           NetworkManager \
           bind-utils \
           weechat \
           make \
           docker \
           nodejs \
           sbcl \
           rustup \
           brightnessctl \
           acpi \
           numlockx \
           chrony \
           btrfs-progs \
           ntfs-3g \
           mtools \
           dosfstools \
           exfat-utils \
           android-tools \
           rlwrap \
           neofetch \
           wget \
           curl \
           openssh

tw_log "Installing graphical packages..."
tw_execute sudo xbps-install -S \
           sct \
           onboard \
           picom \
           i3 \
           i3status \
           i3lock \
           xfce4 \
           feh \
           dmenu \
           rofi \
           kitty \
           xsel \
           udiskie \
           gparted \
           Thunar \
           gvfs \
           syncthing-gtk \
           keepassxc \
           thunderbird \
           transmission-gtk \
           qemu \
           virt-manager \
           libreoffice \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           pavucontrol \
           gstreamer1 \
           pipewire \
           alsa-pipewire \
           libspa-bluetooth \
           easyeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs \
           peek \
           steam \
           lutris \
           gamehub \
           barrier

tw_log "The following packages are absent on Void repos:"
tw_log "brave, authy, tunnelbear, rememberthemilk, dynalist, pcloud, balena-etcher, nomachine, edex-ui"

tw_log "Installing packages through flatpak..."
tw_execute ~/.bin/linux/mt-flatpak-install postman com.getpostman.Postman
tw_execute ~/.bin/linux/mt-flatpak-install element im.riot.Riot

tw_log "Performing a few package-dependent configs..."
tw_log "Adding user to group 'libvirt' for virt-manager..."
tw_execute sudo usermod -aG libvirt ismail
