#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo apt install \
           cryptsetup \
           efibootmgr \
           tmux \
           fish \
           fd-find \
           exa \
           bat \
           ncdu \
           ripgrep \
           fzf \
           vim \
           emacs \
           mpv \
           aspell \
           aspell-en \
           git \
           tig \
           ranger \
           cryfs \
           rsync \
           zip \
           unzip \
           btop \
           psmisc \
           udisks2 \
           network-manager \
           dnsutils \
           weechat \
           make \
           docker \
           npm \
           sbcl \
           cargo \
           brightnessctl \
           acpi \
           btrfs-progs \
           ntfs-3g \
           mtools \
           dosfstools \
           exfat-utils \
           android-platform-system-core \
           rlwrap \
           neofetch \
           wget \
           curl \
           ssh

tw_log "Installing graphical packages..."
tw_execute sudo apt install \
           sct \
           onboard \
           compton \
           i3 \
           xss-lock \
           xfce4 \
           feh \
           rofi \
           kitty \
           xsel \
           udiskie \
           gparted \
           thunar \
           gvfs \
           keepassxc \
           thunderbird \
           transmission \
           virt-manager \
           libreoffice \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           pavucontrol \
           pipewire \
           pipewire-pulse \
           pipewire-alsa \
           easyeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs-studio \
           peek \
           steam \
           lutris \
           barrier

tw_log "Installing more packages..."
tw_execute sudo apt install \
           syncthing-gtk \
           numlockx

# TODO: Fix for Debian: find a way to install the below graphical packages
tw_log "The following packages were not found on Debian archives:"
tw_log "brave, authy, tunnelbear, rememberthemilk, dynalist, pcloud, key-mon, gamehub, balena-etcher, nomachine, edex-ui"

# TODO: Fix for Debian: picom is here compton
# TODO: Fix for Debian: dmenu is here i3-dmenu-desktop

tw_log "Installing packages through flatpak..."
tw_execute ~/.bin/linux/mt-flatpak-install postman com.getpostman.Postman
tw_execute ~/.bin/linux/mt-flatpak-install schildi chat.schildi.desktop

tw_log "Performing a few package-dependent configs..."
tw_log "Adding user to group 'libvirt' for virt-manager..."
tw_execute sudo usermod -aG libvirt ismail
tw_log "Creating soft-links to unusually named binary packages"
tw_execute sudo ln -s "$(which fdfind)" "$(which fdfind | xargs readlink -f | xargs dirname)/fd"
tw_execute sudo ln -s "$(which batcat)" "$(which batcat | xargs readlink -f | xargs dirname)/bat"
