#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo pacman -S \
           archlinux-keyring \
           cryptsetup \
           efibootmgr \
           polkit \
           tmux \
           fish \
           fd \
           lsd \
           bat \
           ncdu \
           ripgrep \
           fzf \
           vim \
           emacs \
           mpv \
           aspell \
           aspell-en \
           git \
           tig \
           ranger \
           cryfs \
           rsync \
           zip \
           unzip \
           btop \
           psmisc \
           udisks2 \
           networkmanager \
           bind \
           weechat \
           make \
           docker \
           npm \
           sbcl \
           rustup \
           brightnessctl \
           acpi \
           btrfs-progs \
           ntfs-3g \
           mtools \
           dosfstools \
           exfat-utils \
           android-tools \
           rlwrap \
           neofetch \
           wget \
           curl \
           openssh

tw_log "Installing graphical packages..."
tw_execute sudo pacman -S \
           onboard \
           picom \
           i3 \
           xfce4 \
           feh \
           dmenu \
           rofi \
           kitty \
           xsel \
           udiskie \
           gparted \
           thunar \
           gvfs \
           brave \
           keepassxc \
           thunderbird \
           transmission-gtk \
           virt-manager \
           libreoffice-fresh \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           pavucontrol \
           gstreamer \
           pipewire \
           pipewire-pulse \
           pipewire-alsa \
           easyeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs-studio \
           peek \
           steam \
           lutris \
           barrier

tw_log "Installing packages from AUR..."
tw_execute paru -S --mflags --skipinteg \
           sct \
           authy \
           tunnelbear \
           rememberthemilk \
           dynalist-desktop \
           syncthing-gtk \
           pcloud-drive \
           gamehub \
           key-mon \
           balena-etcher \
           nomachine \
           systemd-numlockontty \
           edex-ui

# Manual packages
# (None yet)

# Missing packages / Find alternative
# - Google Drive
# - Origin
# - Sony Remote play
# - licecap
# - Razer Synapse

# Inbuilt packages
# (None yet)

tw_log "Installing packages through flatpak..."
tw_execute ~/.bin/linux/mt-flatpak-install postman com.getpostman.Postman
tw_execute ~/.bin/linux/mt-flatpak-install schildi chat.schildi.desktop

tw_log "Performing a few package-dependent configs..."
tw_log "Adding user to group 'libvirt' for virt-manager..."
tw_execute sudo usermod -aG libvirt ismail
# TODO: Implement setting the default web-browser
